version: '2'
services:

  node-internal-apvs:
    build: .
    volumes:
      - "./gulpfile.js:/usr/src/app/gulpfile.js"
      - "./nodemon.json:/usr/src/app/nodemon.json"
      - "./app:/usr/src/app/app"
      - "./cache_node_modules:/usr/src/app/node_modules"
      - "./logs:/usr/src/app/logs"
    ports:
      - "3001:3001"
    environment:
    - LOGGING_PATH=/usr/src/app/logs/internal-web.log
    - APVS_DATABASE
    - APVS_DATABASE_SERVER
    - APVS_INT_WEB_USERNAME
    - APVS_INT_WEB_PASSWORD
    - APVS_INT_MIGRATION_USERNAME
    - APVS_INT_MIGRATION_PASSWORD
