version: '3'
services:
  help-with-prison-visits-internal:
    build:
      context: .
    volumes:
      - "./gulpfile.js:/usr/src/app/gulpfile.js"
      - "./nodemon.json:/usr/src/app/nodemon.json"
      - "./app:/usr/src/app/app"
      - "./logs:/usr/src/app/logs"
      - "./uploads:/usr/src/app/uploads"
    ports:
      - "3001:3001"
    env_file: ./.env
