---
# Values here are the same across all environments
generic-service:
  nameOverride: help-with-prison-visits-internal

  image:
    repository: quay.io/hmpps/help-with-prison-visits-internal
    tag: app_version    # override at deployment time
    port: 3001

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/custom-http-errors: "418"
    tlsSecretName: help-with-prison-visits-internal-cert
    path: /

  livenessProbe:
    httpGet:
      path: /status
      port: http
  
  readinessProbe:
    httpGet:
      path: /status
      port: http
  
  env:
    FILE_UPLOAD_LOCATION: '/data'
    FILE_ARCHIVE_LOCATION: '/archive'
    LOGGING_LEVEL: 'DEBUG'
    APVS_MOJ_SSO_AUTHENTICATION_ENABLED: 'true'
    APVS_MOJ_SSO_TOKEN_PATH: '/oauth/token'
    APVS_MOJ_SSO_AUTHORIZE_PATH: '/oauth/authorize'
    APVS_MOJ_SSO_USER_PATH_PREFIX: /api/user
    APVS_MOJ_SSO_USER_DETAILS_PATH: '/me'
    APVS_MOJ_SSO_USER_EMAIL_PATH: '/email'
    APVS_MOJ_SSO_USER_ROLES_PATH: '/me/roles'
    APVS_MOJ_SSO_LOGOUT_PATH: '/logout'
    APVS_INT_SECURE_COOKIE: 'true'

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    help-with-prison-visits-internal:
      APVS_APP_INSIGHTS_INSTRUMENTATION_KEY: "APVS_APP_INSIGHTS_INSTRUMENTATION_KEY"
      APVS_MOJ_SSO_CLIENT_ID: "APVS_MOJ_SSO_CLIENT_ID"
      APVS_MOJ_SSO_CLIENT_SECRET: "APVS_MOJ_SSO_CLIENT_SECRET"
      APVS_MOJ_SSO_SESSION_SECRET: "APVS_MOJ_SSO_SESSION_SECRET"
      APVS_INT_APPLICATION_SECRET: "APVS_INT_APPLICATION_SECRET"
    #rds-instance-output:
    #  APVS_DATABASE: "database_name"
    #  APVS_DATABASE_SERVER: 'rds_instance_address'
    #  APVS_INT_WEB_USERNAME: 'database_username'
    #  APVS_INT_WEB_PASSWORD: 'database_password'
    azure-sqlserver:
      APVS_DATABASE: "APVS_DATABASE"
      APVS_DATABASE_SERVER: "APVS_DATABASE_SERVER"
      APVS_INT_WEB_USERNAME: "APVS_EXT_WEB_USERNAME"
      APVS_INT_WEB_PASSWORD: "APVS_EXT_WEB_PASSWORD"
